version: '3'

services:
  deletable-api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: deletable-api
    depends_on:
      - deletable-pg
    env_file:
      - ./api/.env
    ports:
      - "4000:4000"
    restart: unless-stopped
    volumes:
      - /app/api/node_modules   # volume lives here
      - .:/app                  # monorepo

  # deletable-web:
  #   build:
  #     context: ./web
  #     dockerfile: Dockerfile.dev
  #   container_name: deletable-web
  #   env_file:
  #     - ./web/.env
  #   ports:
  #     - "5173:5173"
  #   restart: unless-stopped
  #   volumes:
  #     - /app/web/node_modules   # volume here
  #     - .:/app                  # monorepo

  deletable-pg:
    image: postgres:16
    container_name: deletable-pg
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: deletable
    volumes:
      - deletable_pg_data:/var/lib/postgresql/data

volumes:
  deletable_pg_data:
