/**
 * @type {import('node-pg-migrate').ColumnDefinitions | undefined}
 */
export const shorthands = undefined;

/**
 * @param pgm {import('node-pg-migrate').MigrationBuilder}
 * @param run {() => void | undefined}
 * @returns {Promise<void> | void}
 */
export const up = (pgm) => {
  pgm.sql(`
    CREATE TABLE roles (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      created_at TIMESTAMPTZ DEFAULT now(),
      updated_at TIMESTAMPTZ DEFAULT now()
    );

    CREATE TABLE accounts (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      created_at TIMESTAMPTZ DEFAULT now(),
      updated_at TIMESTAMPTZ DEFAULT now()
    );

    CREATE TABLE users (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      first_name TEXT NOT NULL,
      last_name TEXT NOT NULL,
      email TEXT UNIQUE NOT NULL,
      role_id BIGINT NOT NULL REFERENCES roles(id),
      account_id BIGINT NOT NULL REFERENCES accounts(id),
      created_at TIMESTAMPTZ DEFAULT now(),
      updated_at TIMESTAMPTZ DEFAULT now()
    );

    CREATE TABLE services (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      account_id BIGINT NOT NULL REFERENCES accounts(id),
      created_at TIMESTAMPTZ DEFAULT now(),
      updated_at TIMESTAMPTZ DEFAULT now(),

      CONSTRAINT uq_service UNIQUE (account_id, name)
    );

    CREATE TABLE endpoints (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      account_id BIGINT NOT NULL REFERENCES accounts(id),
      service_id BIGINT NOT NULL REFERENCES services(id),
      method TEXT NOT NULL,
      path TEXT NOT NULL,
      first_seen_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
      last_seen_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
      total_hits             BIGINT NOT NULL DEFAULT 0,

      CONSTRAINT uq_endpoint UNIQUE (service_id, method, path)
    );

    CREATE TYPE field_context AS ENUM (
      'request_body',
      'response_body',
      'query_param',
      'header'
    );

    CREATE TABLE field_usage (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      account_id BIGINT NOT NULL REFERENCES accounts(id),
      service_id BIGINT NOT NULL REFERENCES services(id),
      endpoint_id BIGINT NOT NULL REFERENCES endpoints(id),
      context field_context NOT NULL,
      field_path TEXT NOT NULL,
      first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      type_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
      total_observations BIGINT NOT NULL DEFAULT 0,

      CONSTRAINT uq_field_usage UNIQUE (endpoint_id, context, field_path)
    );

    CREATE TABLE client_signatures (
      id           BIGSERIAL PRIMARY KEY,
      service_id   BIGINT NOT NULL REFERENCES services(id),
      signature    TEXT NOT NULL,      -- e.g. hash of UA + app version + whatever
      label        TEXT NULL,          -- optional human-friendly label later
      first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      last_seen_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

      CONSTRAINT uq_client_signature UNIQUE (service_id, signature)
    );

    CREATE TABLE endpoint_client_usage (
      endpoint_id         BIGINT NOT NULL REFERENCES endpoints(id),
      client_signature_id BIGINT NOT NULL REFERENCES client_signatures(id),
      total_hits          BIGINT NOT NULL DEFAULT 0,
      first_seen_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
      last_seen_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

      PRIMARY KEY (endpoint_id, client_signature_id)
    );

    CREATE TABLE IF NOT EXISTS ingest_batches (
      id BIGSERIAL PRIMARY KEY,
      service_id BIGINT NOT NULL REFERENCES services(id),
      batch_id UUID NOT NULL,
      received_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      CONSTRAINT uq_ingest_batches UNIQUE (service_id, batch_id)
    );

    CREATE INDEX idx_services_account_id ON services (account_id);

    CREATE INDEX idx_endpoints_account_id ON endpoints (account_id);
    CREATE INDEX idx_endpoints_service_id ON endpoints (service_id);

    CREATE INDEX idx_field_usage_account_id ON field_usage (account_id);
    CREATE INDEX idx_field_usage_service_id ON field_usage (service_id);
    CREATE INDEX idx_field_usage_endpoint_id ON field_usage (endpoint_id);

    CREATE INDEX idx_client_signatures_service_id ON client_signatures (service_id);

    CREATE INDEX idx_endpoint_client_usage_endpoint_id ON endpoint_client_usage (endpoint_id);
    CREATE INDEX idx_endpoint_client_usage_client_id ON endpoint_client_usage (client_signature_id);
  `);
};

/**
 * @param pgm {import('node-pg-migrate').MigrationBuilder}
 * @param run {() => void | undefined}
 * @returns {Promise<void> | void}
 */
export const down = (pgm) => {
  pgm.sql(`
    DROP TABLE endpoint_client_usage;
    DROP TABLE client_signatures;
    DROP TABLE field_usage;
    DROP TABLE endpoints;
    DROP TABLE services;
    DROP TABLE users;
    DROP TABLE accounts;
    DROP TABLE roles;

    DROP TYPE field_context;
  `);
};
