/**
 * @type {import('node-pg-migrate').ColumnDefinitions | undefined}
 */
exports.shorthands = undefined;

/**
 * @param pgm {import('node-pg-migrate').MigrationBuilder}
 * @param run {() => void | undefined}
 * @returns {Promise<void> | void}
 */
exports.up = (pgm) => {
  pgm.sql(`
    CREATE TABLE roles (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      created_at TIMESTAMPTZ DEFAULT now(),
      updated_at TIMESTAMPTZ DEFAULT now()
    );

    CREATE TABLE accounts (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      created_at TIMESTAMPTZ DEFAULT now(),
      updated_at TIMESTAMPTZ DEFAULT now()
    );

    CREATE TABLE users (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      first_name TEXT NOT NULL,
      last_name TEXT NOT NULL,
      email TEXT UNIQUE NOT NULL,
      role_id BIGINT NOT NULL REFERENCES roles(id),
      account_id BIGINT NOT NULL REFERENCES accounts(id),
      created_at TIMESTAMPTZ DEFAULT now(),
      updated_at TIMESTAMPTZ DEFAULT now()
    );

    CREATE TABLE applications (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      account_id BIGINT NOT NULL REFERENCES accounts(id),
      created_at TIMESTAMPTZ DEFAULT now(),
      updated_at TIMESTAMPTZ DEFAULT now(),

      CONSTRAINT uq_application UNIQUE (account_id, name)
    );

    CREATE TABLE endpoints (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      account_id BIGINT NOT NULL REFERENCES accounts(id),
      application_id BIGINT NOT NULL REFERENCES applications(id),
      method TEXT NOT NULL,
      path TEXT NOT NULL,
      first_seen_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
      last_seen_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
      total_hits             BIGINT NOT NULL DEFAULT 0,

      CONSTRAINT uq_endpoint UNIQUE (application_id, method, path)
    );

    CREATE TYPE field_context AS ENUM (
      'request_body',
      'response_body',
      'query_param',
      'header'
    );

    CREATE TABLE field_usage (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      account_id BIGINT NOT NULL REFERENCES accounts(id),
      application_id BIGINT NOT NULL REFERENCES applications(id),
      endpoint_id BIGINT NOT NULL REFERENCES endpoints(id),
      context field_context NOT NULL,
      field_path TEXT NOT NULL,
      first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      type_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
      total_observations BIGINT NOT NULL DEFAULT 0,

      CONSTRAINT uq_field_usage UNIQUE (endpoint_id, context, field_path)
    );

    CREATE TABLE client_signatures (
      id           BIGSERIAL PRIMARY KEY,
      application_id   BIGINT NOT NULL REFERENCES applications(id),
      signature    TEXT NOT NULL,      -- e.g. hash of UA + app version + whatever
      label        TEXT NULL,          -- optional human-friendly label later
      first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      last_seen_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

      CONSTRAINT uq_client_signature UNIQUE (application_id, signature)
    );

    CREATE TABLE endpoint_client_usage (
      endpoint_id         BIGINT NOT NULL REFERENCES endpoints(id),
      client_signature_id BIGINT NOT NULL REFERENCES client_signatures(id),
      total_hits          BIGINT NOT NULL DEFAULT 0,
      first_seen_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
      last_seen_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

      PRIMARY KEY (endpoint_id, client_signature_id)
    );

    CREATE TABLE IF NOT EXISTS ingest_batches (
      id BIGSERIAL PRIMARY KEY,
      application_id BIGINT NOT NULL REFERENCES applications(id),
      batch_id UUID NOT NULL,
      received_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      CONSTRAINT uq_ingest_batches UNIQUE (application_id, batch_id)
    );

    CREATE TABLE IF NOT EXISTS application_api_keys (
      id BIGSERIAL PRIMARY KEY,
      application_id BIGINT NOT NULL REFERENCES applications(id),
      public_key TEXT NOT NULL,
      secret_hash TEXT NOT NULL,
      status TEXT NOT NULL,
      account_id BIGINT NOT NULL REFERENCES accounts(id),
      created_at TIMESTAMPTZ DEFAULT now(),
      updated_at TIMESTAMPTZ DEFAULT now()
    );

    CREATE INDEX idx_applications_account_id ON applications (account_id);

    CREATE INDEX idx_endpoints_account_id ON endpoints (account_id);
    CREATE INDEX idx_endpoints_application_id ON endpoints (application_id);

    CREATE INDEX idx_field_usage_account_id ON field_usage (account_id);
    CREATE INDEX idx_field_usage_applicaiton_id ON field_usage (application_id);
    CREATE INDEX idx_field_usage_endpoint_id ON field_usage (endpoint_id);

    CREATE INDEX idx_client_signatures_application_id ON client_signatures (application_id);

    CREATE INDEX idx_endpoint_client_usage_endpoint_id ON endpoint_client_usage (endpoint_id);
    CREATE INDEX idx_endpoint_client_usage_client_id ON endpoint_client_usage (client_signature_id);
  `);
};

/**
 * @param pgm {import('node-pg-migrate').MigrationBuilder}
 * @param run {() => void | undefined}
 * @returns {Promise<void> | void}
 */
exports.down = (pgm) => {
  pgm.sql(`
    DROP TABLE application_api_key;
    DROP TABLE ingest_batches;
    DROP TABLE endpoint_client_usage;
    DROP TABLE client_signatures;
    DROP TABLE field_usage;
    DROP TABLE endpoints;
    DROP TABLE applications;
    DROP TABLE users;
    DROP TABLE accounts;
    DROP TABLE roles;

    DROP TYPE field_context;
  `);
};
